POST http://localhost:8080/holder
Content-Type: application/json

{
  "holderName": "동기",
  "phoneNumber": "01033334444",
  "address": "사당로"
}

###

POST http://localhost:8080/account
Content-Type: application/json

{
  "holderId": "68e740ff-17c2-4dba-91f5-b13b1d19df12"
}

###

POST http://localhost:8080/deposit
Content-Type: application/json

{
  "accountId": "620c44d3-50fd-4fd4-a771-f70dea570bab",
  "holderId": "68e740ff-17c2-4dba-91f5-b13b1d19df12",
  "amount": "12345080",
  "action": "deposit"
}

###

POST http://localhost:8080/withdraw
Content-Type: application/json

{
  "accountId": "620c44d3-50fd-4fd4-a771-f70dea570bab",
  "holderId": "68e740ff-17c2-4dba-91f5-b13b1d19df12",
"amount": "323",
"action": "withdrawal"
}