POST http://localhost:8080/holder
Content-Type: application/json

{
  "holderName": "동기",
  "phoneNumber": "01033334444",
  "address": "사당로"
}

###

POST http://localhost:8080/account
Content-Type: application/json

{
  "holderId": "e519695b-8cc0-4fa2-a8a9-8008dcebabf5"
}

###

POST http://localhost:8080/deposit
Content-Type: application/json

{
  "accountId": "ee9f3682-b174-4235-b52f-6e56eb88a7da",
  "holderId": "e519695b-8cc0-4fa2-a8a9-8008dcebabf5",
  "amount": "551222",
  "action": "deposit"
}

###

POST http://localhost:8080/withdraw
Content-Type: application/json

{
  "accountId": "ee9f3682-b174-4235-b52f-6e56eb88a7da",
  "holderId": "e519695b-8cc0-4fa2-a8a9-8008dcebabf5",
"amount": "323",
"action": "withdrawal"
}